-- Generated by CSharp.lua Compiler 1.0.0.0
local System = System;
System.namespace("CSharpLua.LuaAst", function (namespace) 
    namespace.class("LuaArgumentSyntax", function (namespace) 
        local Render, __ctor__;
        Render = function (this, renderer) 
            renderer:Render8(this);
        end;
        __ctor__ = function (this, expression) 
            if expression == nil then
                System.throw(System.ArgumentNullException("expression"));
            end
            this.Expression = expression;
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaSyntaxNode
            }, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
    namespace.class("LuaArgumentListSyntax", function (namespace) 
        local getOpenParenToken, getCloseParenToken, Render, __ctor__;
        getOpenParenToken = function (this) 
            return "(" --[[Tokens.OpenParentheses]];
        end;
        getCloseParenToken = function (this) 
            return ")" --[[Tokens.CloseParentheses]];
        end;
        Render = function (this, renderer) 
            renderer:Render7(this);
        end;
        __ctor__ = function (this) 
            this.Arguments = CSharpLua.LuaAst.LuaSyntaxList_1(CSharpLua.LuaAst.LuaArgumentSyntax)();
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaSyntaxNode
            }, 
            getOpenParenToken = getOpenParenToken, 
            getCloseParenToken = getCloseParenToken, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
end);
