-- Generated by CSharp.lua Compiler 1.0.0.0
local System = System;
System.namespace("CSharpLua.LuaAst", function (namespace) 
    namespace.class("LuaBlockSyntax", function (namespace) 
        local Render, __ctor__;
        __ctor__ = function (this) 
            this.Statements = CSharpLua.LuaAst.LuaSyntaxList_1(CSharpLua.LuaAst.LuaStatementSyntax)();
        end;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaStatementSyntax
            }, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
    namespace.class("LuaBlockBlockSyntax", function (namespace) 
        local Render, __init__, __ctor__;
        __init__ = function (this) 
            this.Body = System.create(CSharpLua.LuaAst.LuaBlockSyntax(), function (default) 
                default.OpenBraceToken = "do" --[[Keyword.Do]];
                default.CloseBraceToken = "end" --[[Keyword.End]];
            end);
        end;
        __ctor__ = function (this, block) 
            __init__(this);
            if block == nil then
                System.throw(System.ArgumentNullException("block"));
            end
            this.Body.Statements:AddRange(block.Statements);
        end;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaStatementSyntax
            }, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
end);
