-- Generated by CSharp.lua Compiler 1.0.0.0
local System = System;
local CSharpLuaLuaAst;
System.usingDeclare(function (global) 
    CSharpLuaLuaAst = CSharpLua.LuaAst;
end);
System.namespace("CSharpLua.LuaAst", function (namespace) 
    namespace.class("LuaBlockSyntax", function (namespace) 
        local Render, __ctor__;
        Render = function (this, renderer) 
            renderer:Render13(this);
        end;
        __ctor__ = function (this) 
            this.Statements = CSharpLuaLuaAst.LuaSyntaxList_1(CSharpLuaLuaAst.LuaStatementSyntax)();
        end;
        return {
            __inherits__ = {
                CSharpLuaLuaAst.LuaStatementSyntax
            }, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
    namespace.class("LuaBlockStatementSyntax", function (namespace) 
        local Render, __ctor__;
        Render = function (this, renderer) 
            renderer:Render14(this);
        end;
        __ctor__ = function (this) 
            this.OpenBraceToken = "do" --[[Keyword.Do]];
            this.CloseBraceToken = "end" --[[Keyword.End]];
        end;
        return {
            __inherits__ = {
                CSharpLuaLuaAst.LuaBlockSyntax
            }, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
end);
