-- Generated by CSharp.lua Compiler 1.0.0.0
local System = System;
local Linq = System.Linq.Enumerable;
System.namespace("CSharpLua.LuaAst", function (namespace) 
    namespace.class("LuaInvocationExpressionSyntax", function (namespace) 
        local AddArgument, Render, __init__, __ctor1__, __ctor2__, __ctor3__, __ctor4__, __ctor5__, 
        __ctor6__;
        __init__ = function (this) 
            this.ArgumentList = CSharpLua.LuaAst.LuaArgumentListSyntax();
        end;
        __ctor1__ = function (this, expression) 
            __init__(this);
            if expression == nil then
                System.throw(System.ArgumentNullException("expression"));
            end
            this.Expression = expression;
        end;
        __ctor2__ = function (this, expression, argument) 
            __ctor1__(this, expression);
            AddArgument(this, argument);
        end;
        __ctor3__ = function (this, expression, argument1, argument2) 
            __ctor1__(this, expression);
            AddArgument(this, argument1);
            AddArgument(this, argument2);
        end;
        __ctor4__ = function (this, expression, argument1, argument2, argument3) 
            __ctor1__(this, expression);
            AddArgument(this, argument1);
            AddArgument(this, argument2);
            AddArgument(this, argument3);
        end;
        __ctor5__ = function (this, expression, arguments) 
            __ctor1__(this, expression);
            this.ArgumentList.Arguments:AddRange(Linq.Select(arguments, function (i) return CSharpLua.LuaAst.LuaArgumentSyntax(i); end, CSharpLua.LuaAst.LuaArgumentSyntax));
        end;
        __ctor6__ = function (this, expression, arguments) 
            __ctor5__(this, expression, System.cast(System.IEnumerable_1(CSharpLua.LuaAst.LuaExpressionSyntax), arguments));
        end;
        AddArgument = function (this, argument) 
            this.ArgumentList.Arguments:Add(CSharpLua.LuaAst.LuaArgumentSyntax(argument));
        end;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaExpressionSyntax
            }, 
            AddArgument = AddArgument, 
            Render = Render, 
            __ctor__ = {
                __ctor1__, 
                __ctor2__, 
                __ctor3__, 
                __ctor4__, 
                __ctor5__, 
                __ctor6__
            }
        };
    end);
end);
