-- Generated by CSharp.lua Compiler 1.0.0.0
local System = System;
System.namespace("CSharpLua.LuaAst", function (namespace) 
    namespace.class("LuaNamespaceDeclarationSyntax", function (namespace) 
        local __ctor__;
        __ctor__ = function (this, name) 
            this:UpdateIdentifiers(name, CSharpLua.LuaAst.LuaIdentifierNameSyntax.System, CSharpLua.LuaAst.LuaIdentifierNameSyntax.Namespace, CSharpLua.LuaAst.LuaIdentifierNameSyntax.Namespace);
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaWrapFunctionStatementSynatx
            }, 
            __ctor__ = __ctor__
        };
    end);
end);
