-- Generated by CSharp.lua Compiler 1.0.0.0
local System = System;
System.namespace("CSharpLua.LuaAst", function (namespace) 
    namespace.class("LuaStatementSyntax", function (namespace) 
        namespace.class("EmptyLuaStatementSyntax", function (namespace) 
            local Render;
            Render = function (this, renderer) 
            end;
            return {
                __inherits__ = {
                    CSharpLua.LuaAst.LuaStatementSyntax
                }, 
                Render = Render
            };
        end);
        local getSemicolonToken, Empty, __staticCtor__;
        getSemicolonToken = function (this) 
            return CSharpLua.LuaAst.Tokens.Semicolon;
        end;
        __staticCtor__ = function (this) 
            Empty = CSharpLua.LuaAst.EmptyLuaStatementSyntax();
            this.Empty = Empty;
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaSyntaxNode
            }, 
            getSemicolonToken = getSemicolonToken, 
            __staticCtor__ = __staticCtor__
        };
    end);
    namespace.class("LuaExpressionStatementSyntax", function (namespace) 
        local Render, __ctor__;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        __ctor__ = function (this, expression) 
            if expression == nil then
                System.throw(System.ArgumentNullException("expression"));
            end
            this.Expression = expression;
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaStatementSyntax
            }, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
    namespace.class("LuaStatementListSyntax", function (namespace) 
        local Render, __ctor__;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        __ctor__ = function (this) 
            this.Statements = System.List(CSharpLua.LuaAst.LuaStatementSyntax)();
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaStatementSyntax
            }, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
    namespace.class("LuaReturnStatementSyntax", function (namespace) 
        local getReturnKeyword, Render, __ctor1__, __ctor2__;
        getReturnKeyword = function (this) 
            return "return" --[[Keyword.Return]];
        end;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        __ctor1__ = function (this, expression) 
            if expression == nil then
                System.throw(System.ArgumentNullException("expression"));
            end
            this.Expression = expression;
        end;
        __ctor2__ = function (this) 
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaStatementSyntax
            }, 
            getReturnKeyword = getReturnKeyword, 
            Render = Render, 
            __ctor__ = {
                __ctor1__, 
                __ctor2__
            }
        };
    end);
    namespace.class("LuaMultipleReturnStatementSyntax", function (namespace) 
        local getReturnKeyword, Render, __ctor__;
        getReturnKeyword = function (this) 
            return "return" --[[Keyword.Return]];
        end;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        __ctor__ = function (this) 
            this.Expressions = CSharpLua.LuaAst.LuaSyntaxList_1(CSharpLua.LuaAst.LuaExpressionSyntax)();
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaStatementSyntax
            }, 
            getReturnKeyword = getReturnKeyword, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
    namespace.class("LuaBreakStatementSyntax", function (namespace) 
        local getBreakKeyword, Render, Statement, __staticCtor__, __ctor__;
        getBreakKeyword = function (this) 
            return "break" --[[Keyword.Break]];
        end;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        __staticCtor__ = function (this) 
            Statement = CSharpLua.LuaAst.LuaBreakStatementSyntax:new(1);
            this.Statement = Statement;
        end;
        __ctor__ = function (this) 
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaStatementSyntax
            }, 
            getBreakKeyword = getBreakKeyword, 
            Render = Render, 
            __staticCtor__ = __staticCtor__, 
            __ctor__ = __ctor__
        };
    end);
    namespace.class("LuaContinueAdapterStatementSyntax", function (namespace) 
        local getBreak, Render, Statement, __staticCtor__, __ctor__;
        getBreak = function (this) 
            return CSharpLua.LuaAst.LuaBreakStatementSyntax.Statement;
        end;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        __staticCtor__ = function (this) 
            Statement = CSharpLua.LuaAst.LuaContinueAdapterStatementSyntax:new(1);
            this.Statement = Statement;
        end;
        __ctor__ = function (this) 
            this.Assignment = CSharpLua.LuaAst.LuaExpressionStatementSyntax(CSharpLua.LuaAst.LuaAssignmentExpressionSyntax(CSharpLua.LuaAst.LuaIdentifierNameSyntax.Continue, CSharpLua.LuaAst.LuaIdentifierNameSyntax.True));
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaStatementSyntax
            }, 
            getBreak = getBreak, 
            Render = Render, 
            __staticCtor__ = __staticCtor__, 
            __ctor__ = __ctor__
        };
    end);
    namespace.class("LuaBlankLinesStatement", function (namespace) 
        local Render, One, __staticCtor__, __ctor__;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        __staticCtor__ = function (this) 
            One = CSharpLua.LuaAst.LuaBlankLinesStatement:new(1, 1);
            this.One = One;
        end;
        __ctor__ = function (this, count) 
            this.Count = count;
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaStatementSyntax
            }, 
            Count = 0, 
            Render = Render, 
            __staticCtor__ = __staticCtor__, 
            __ctor__ = __ctor__
        };
    end);
    namespace.class("LuaShortCommentStatement", function (namespace) 
        local getSingleCommentToken, Render, __ctor__;
        getSingleCommentToken = function (this) 
            return "--" --[[Tokens.ShortComment]];
        end;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        __ctor__ = function (this, comment) 
            this.Comment = comment;
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaStatementSyntax
            }, 
            getSingleCommentToken = getSingleCommentToken, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
    namespace.class("LuaLongCommentStatement", function (namespace) 
        local getOpenCommentToken, getCloseCommentToken, Render, __ctor__;
        getOpenCommentToken = function (this) 
            return "--[[" --[[Tokens.OpenLongComment]];
        end;
        getCloseCommentToken = function (this) 
            return "--]]" --[[Tokens.CloseLongComment]];
        end;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        __ctor__ = function (this, comment) 
            this.Comment = comment;
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaStatementSyntax
            }, 
            getOpenCommentToken = getOpenCommentToken, 
            getCloseCommentToken = getCloseCommentToken, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
    namespace.class("LuaGotoStatement", function (namespace) 
        local getGotoKeyword, Render, __ctor__;
        getGotoKeyword = function (this) 
            return "goto" --[[Keyword.Goto]];
        end;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        __ctor__ = function (this, identifier) 
            if identifier == nil then
                System.throw(System.ArgumentNullException("identifier"));
            end
            this.Identifier = identifier;
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaStatementSyntax
            }, 
            getGotoKeyword = getGotoKeyword, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
    namespace.class("LuaGotoCaseAdapterStatement", function (namespace) 
        local Render, __ctor__;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        __ctor__ = function (this, identifier) 
            if identifier == nil then
                System.throw(System.ArgumentNullException("identifier"));
            end

            local assignment = CSharpLua.LuaAst.LuaAssignmentExpressionSyntax(identifier, CSharpLua.LuaAst.LuaIdentifierNameSyntax.True);
            this.Assignment = CSharpLua.LuaAst.LuaExpressionStatementSyntax(assignment);
            this.GotoStatement = CSharpLua.LuaAst.LuaGotoStatement(identifier);
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaStatementSyntax
            }, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
    namespace.class("LuaLabeledStatement", function (namespace) 
        local getPrefixToken, getSuffixToken, Render, __ctor__;
        getPrefixToken = function (this) 
            return "::" --[[Tokens.Label]];
        end;
        getSuffixToken = function (this) 
            return "::" --[[Tokens.Label]];
        end;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        __ctor__ = function (this, identifier, statement) 
            if identifier == nil then
                System.throw(System.ArgumentNullException("identifier"));
            end
            this.Identifier = identifier;
            this.Statement = statement;
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaStatementSyntax
            }, 
            getPrefixToken = getPrefixToken, 
            getSuffixToken = getSuffixToken, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
end);
