-- Generated by CSharp.lua Compiler 1.0.0.0
local System = System;
System.namespace("CSharpLua.LuaAst", function (namespace) 
    namespace.class("LuaTableInitializerExpression", function (namespace) 
        local getOpenBraceToken, getCloseBraceToken, Render, __ctor__;
        __ctor__ = function (this) 
            this.Items = CSharpLua.LuaAst.LuaSyntaxList_1(CSharpLua.LuaAst.LuaTableItemSyntax)();
        end;
        getOpenBraceToken = function (this) 
            return "{" --[[Tokens.OpenBrace]];
        end;
        getCloseBraceToken = function (this) 
            return "}" --[[Tokens.CloseBrace]];
        end;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaExpressionSyntax
            }, 
            getOpenBraceToken = getOpenBraceToken, 
            getCloseBraceToken = getCloseBraceToken, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
    namespace.class("LuaTableItemSyntax", function (namespace) 
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaSyntaxNode
            }
        };
    end);
    namespace.class("LuaSingleTableItemSyntax", function (namespace) 
        local Render, __ctor__;
        __ctor__ = function (this, expression) 
            if expression == nil then
                System.throw(System.ArgumentNullException("expression"));
            end
            this.Expression = expression;
        end;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaTableItemSyntax
            }, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
    namespace.class("LuaTableKeySyntax", function (namespace) 
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaSyntaxNode
            }
        };
    end);
    namespace.class("LuaTableExpressionKeySyntax", function (namespace) 
        local getOpenBracketToken, getCloseBracketToken, Render, __ctor__;
        __ctor__ = function (this, expression) 
            this.Expression = expression;
        end;
        getOpenBracketToken = function (this) 
            return "[" --[[Tokens.OpenBracket]];
        end;
        getCloseBracketToken = function (this) 
            return "]" --[[Tokens.CloseBracket]];
        end;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaTableKeySyntax
            }, 
            getOpenBracketToken = getOpenBracketToken, 
            getCloseBracketToken = getCloseBracketToken, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
    namespace.class("LuaTableLiteralKeySyntax", function (namespace) 
        local Render, __ctor__;
        __ctor__ = function (this, identifier) 
            this.Identifier = identifier;
        end;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaTableKeySyntax
            }, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
    namespace.class("LuaKeyValueTableItemSyntax", function (namespace) 
        local getOperatorToken, Render, __ctor__;
        __ctor__ = function (this, key, value) 
            this.Key = key;
            this.Value = value;
        end;
        getOperatorToken = function (this) 
            return "=" --[[Tokens.Equals]];
        end;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaTableItemSyntax
            }, 
            getOperatorToken = getOperatorToken, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
    namespace.class("LuaTableIndexAccessExpressionSyntax", function (namespace) 
        local getOpenBracketToken, getCloseBracketToken, Render, __ctor__;
        __ctor__ = function (this, expression, index) 
            if expression == nil then
                System.throw(System.ArgumentNullException("expression"));
            end
            if index == nil then
                System.throw(System.ArgumentNullException("index"));
            end
            this.Expression = expression;
            this.Index = index;
        end;
        getOpenBracketToken = function (this) 
            return "[" --[[Tokens.OpenBracket]];
        end;
        getCloseBracketToken = function (this) 
            return "]" --[[Tokens.CloseBracket]];
        end;
        Render = function (this, renderer) 
            renderer:Render(this);
        end;
        return {
            __inherits__ = {
                CSharpLua.LuaAst.LuaExpressionSyntax
            }, 
            getOpenBracketToken = getOpenBracketToken, 
            getCloseBracketToken = getCloseBracketToken, 
            Render = Render, 
            __ctor__ = __ctor__
        };
    end);
end);
