-- Generated by CSharp.lua Compiler 1.0.0.0
local System = System
local Linq = System.Linq.Enumerable
local CSharpLuaLuaAst
System.usingDeclare(function (global) 
  CSharpLuaLuaAst = CSharpLua.LuaAst
end)
System.namespace("CSharpLua.LuaAst", function (namespace) 
  namespace.class("LuaBlockSyntax", function (namespace) 
    local Render, AddLocalArea, __init__, __ctor__
    __init__ = function (this) 
      this.Statements = CSharpLuaLuaAst.LuaSyntaxList_1(CSharpLuaLuaAst.LuaStatementSyntax)()
    end
    __ctor__ = function (this) 
      __init__(this)
      CSharpLuaLuaAst.LuaStatementSyntax.__ctor__(this)
    end
    Render = function (this, renderer) 
      renderer:Render12(this)
    end
    AddLocalArea = function (this, name) 
      local localArea = System.as(Linq.FirstOrDefault(this.Statements), CSharpLuaLuaAst.LuaLocalAreaSyntax)
      if localArea == nil then
        localArea = CSharpLuaLuaAst.LuaLocalAreaSyntax()
        this.Statements:Insert(0, localArea)
      end
      localArea.Variables:Add(name)
    end
    return {
      __inherits__ = function (global) 
        return {
          global.CSharpLua.LuaAst.LuaStatementSyntax
        }
      end, 
      Render = Render, 
      AddLocalArea = AddLocalArea, 
      __ctor__ = __ctor__
    }
  end)
  namespace.class("LuaBlockStatementSyntax", function (namespace) 
    local Render, __ctor__
    __ctor__ = function (this) 
      this.__base__.__ctor__(this)
      this.OpenBraceToken = "do" --[[Keyword.Do]]
      this.CloseBraceToken = "end" --[[Keyword.End]]
    end
    Render = function (this, renderer) 
      renderer:Render13(this)
    end
    return {
      __inherits__ = function (global) 
        return {
          global.CSharpLua.LuaAst.LuaBlockSyntax
        }
      end, 
      Render = Render, 
      __ctor__ = __ctor__
    }
  end)
end)
