-- Generated by CSharp.lua Compiler 1.0.0.0
local System = System;
local Linq = System.Linq.Enumerable;
local CSharpLuaLuaAst;
System.usingDeclare(function (global) 
    CSharpLuaLuaAst = CSharpLua.LuaAst;
end);
System.namespace("CSharpLua.LuaAst", function (namespace) 
    namespace.class("LuaInvocationExpressionSyntax", function (namespace) 
        local AddArgument, AddArguments, Render, __init__, __ctor1__, __ctor2__, __ctor3__, __ctor4__, 
        __ctor5__, __ctor6__;
        AddArgument = function (this, argument) 
            this.ArgumentList.Arguments:Add1(CSharpLuaLuaAst.LuaArgumentSyntax(argument));
        end;
        AddArguments = function (this, arguments) 
            this.ArgumentList.Arguments:AddRange1(Linq.Select(arguments, function (i) return CSharpLuaLuaAst.LuaArgumentSyntax(i); end, CSharpLuaLuaAst.LuaArgumentSyntax));
        end;
        Render = function (this, renderer) 
            renderer:Render4(this);
        end;
        __init__ = function (this) 
            this.ArgumentList = CSharpLuaLuaAst.LuaArgumentListSyntax();
        end;
        __ctor1__ = function (this, expression) 
            __init__(this);
            CSharpLuaLuaAst.LuaExpressionSyntax.__ctor__[1](this);
            if expression == nil then
                System.throw(System.ArgumentNullException("expression"));
            end
            this.Expression = expression;
        end;
        __ctor2__ = function (this, expression, argument) 
            __ctor1__(this, expression);
            AddArgument(this, argument);
        end;
        __ctor3__ = function (this, expression, argument1, argument2) 
            __ctor1__(this, expression);
            AddArgument(this, argument1);
            AddArgument(this, argument2);
        end;
        __ctor4__ = function (this, expression, argument1, argument2, argument3) 
            __ctor1__(this, expression);
            AddArgument(this, argument1);
            AddArgument(this, argument2);
            AddArgument(this, argument3);
        end;
        __ctor5__ = function (this, expression, arguments) 
            __ctor1__(this, expression);
            AddArguments(this, arguments);
        end;
        __ctor6__ = function (this, expression, arguments) 
            __ctor1__(this, expression);
            AddArguments(this, arguments);
        end;
        return {
            __inherits__ = function () 
                return {
                    CSharpLuaLuaAst.LuaExpressionSyntax
                };
            end, 
            AddArgument = AddArgument, 
            AddArguments = AddArguments, 
            Render = Render, 
            __ctor__ = {
                __ctor1__, 
                __ctor2__, 
                __ctor3__, 
                __ctor4__, 
                __ctor5__, 
                __ctor6__
            }
        };
    end);
end);
